---
- name: Create initial empty partitioning table...
  become: yes
  command: sgdisk -og {{ install_disk }}
  
- name: Create BIOS boot partition...
  become: yes
  command: sgdisk -n 1:0:+1M -c 1:"BIOS Boot Partition" -t 1:ef02 {{ install_disk }}
  
- name: Create EFI boot partition...
  become: yes
  command: sgdisk -n 2:0:+256M -c 2:"EFI System Partition" -t 2:ef00 {{ install_disk }}
  
- name: Create Linux boot partition...
  become: yes
  command: sgdisk -n 3:0:+256M -c 3:"Linux Boot Partition" -t 3:8300 {{ install_disk }}
  
- name: Create Linux data partition...
  become: yes
  command: sgdisk -n 4:0:0 -c 4:"Linux Data Partition" -t 4:8e00 {{ install_disk }}
  
- name: Formatting BIOS boot partition...
  become: yes
  command: mkfs -t fat -F 32 {{ install_disk }}1
  
- name: Formatting EFI boot partition...
  become: yes
  command: mkfs -t fat -F 32 {{ install_disk }}2
  
- name: Formatting Linux boot partition...
  become: yes
  command: mkfs -t {{ disk_fs }} {{ install_disk }}3
  
- name: Formatting Linux data partition...
  become: yes
  command: mkfs -t {{ disk_fs }} {{ install_disk }}4
  
- name: Mounting root file system...
  become: yes
  mount:
    name: /mnt
    src: "{{ install_disk }}4"
    fstype: "{{ disk_fs }}"
    state: mounted

- name: Mounting /boot file system...
  become: yes
  mount:
    name: /mnt/boot
    src: "{{ install_disk }}3"
    fstype: "{{ disk_fs }}"
    state: mounted

- name: Mounting /boot/EFI file system...
  become: yes
  mount:
    name: /mnt/boot/EFI
    src: "{{ install_disk }}2"
    fstype: vfat
    state: mounted
  
- name: Installing base system...
  become: yes
  command: pacstrap /mnt base
  tags: install
  
- name: Generating fstab...
  become: yes
  command: genfstab -U /mnt >> /mnt/etc/fstab
  tags: install

- name: Setting time zone to Europe/Berlin and syncing hardware clock...
  become: yes
  command: arch-chroot /mnt {{ item }}
  with_items:
    - rm -rf /etc/localtime
    - ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - hwclock --systohc
  tags: chroot

- name: Enabling locales...
  become: yes
  lineinfile: dest=/mnt/etc/locale.gen state=present line={{ item }}
  with_items:
    - de_DE.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
  tags: chroot

- name: Generating locale files...
  become: yes
  command: arch-chroot /mnt {{ item }}
  with_items:
    - locale-gen
  tags: chroot

- name: Setting the default locale to en_US...
  become: yes
  lineinfile: dest=/mnt/etc/locale.conf state=present line={{ item }} create=yes
  with_items:
    - LANG=en_US.UTF-8
  tags: chroot

- name: Setting the default vconsole locale....
  become: yes
  lineinfile: dest=/mnt/etc/vconsole.conf state=present line="KEYMAP=us" create=yes
  tags: chroot

- name: Setting the hostname of the new computer...
  become: yes
  lineinfile: dest=/mnt/etc/hostname state=present line="{{ new_hostname }}" create=yes
  tags: chroot

- name: Setting the hostname of the new computer...
  become: yes
  lineinfile: dest=/mnt/etc/hosts state=present line="127.0.0.1 {{ new_hostname }}.local {{ new_hostname }}" create=yes
  tags: chroot
